# SPDX-FileCopyrightText: 2024 KindSpells Labs S.L.
#
# SPDX-License-Identifier: MIT

name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository # v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install PNPM # v6.0.10
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86

      - name: Use Node.js 22 # v7.0.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish to NPM registry
        run: pnpm publish --provenance --no-git-checks --access public
        working-directory: ./@jacobtread/astro-shield
        env:
          NPM_CONFIG_PROVENANCE: "true"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
